
export interface Emoji {
  emoji: string;
  name: string;
}
export interface EmojiCategory {
  name: string;
  emojis: Emoji[];
}

export const EMOJI_DATA: EmojiCategory[] = [
  {
    name: 'Smileys & Emotion',
    emojis: [
      { emoji: '😀', name: 'grinning face' }, { emoji: '😃', name: 'grinning face with big eyes' }, { emoji: '😄', name: 'grinning face with smiling eyes' },
      { emoji: '😁', name: 'beaming face with smiling eyes' }, { emoji: '😆', name: 'grinning squinting face' }, { emoji: '😅', name: 'grinning face with sweat' },
      { emoji: '🤣', name: 'rolling on the floor laughing' }, { emoji: '😂', name: 'face with tears of joy' }, { emoji: '🙂', name: 'slightly smiling face' },
      { emoji: '🙃', name: 'upside-down face' }, { emoji: '😉', name: 'winking face' }, { emoji: '😊', name: 'smiling face with smiling eyes' },
      { emoji: '😇', name: 'smiling face with halo' }, { emoji: '🥰', name: 'smiling face with hearts' }, { emoji: '😍', name: 'smiling face with heart-eyes' },
      { emoji: '🤩', name: 'star-struck' }, { emoji: '😘', name: 'face blowing a kiss' }, { emoji: '😗', name: 'kissing face' }, { emoji: '😚', name: 'kissing face with closed eyes' },
      { emoji: '😙', name: 'kissing face with smiling eyes' }, { emoji: '😋', name: 'face savoring food' }, { emoji: '😛', name: 'face with tongue' },
      { emoji: '😜', name: 'winking face with tongue' }, { emoji: '🤪', name: 'zany face' }, { emoji: '🤨', name: 'face with raised eyebrow' },
      { emoji: '🧐', name: 'face with monocle' }, { emoji: '🤓', name: 'nerd face' }, { emoji: '😎', name: 'smiling face with sunglasses' },
      { emoji: '🥳', name: 'partying face' }, { emoji: '😏', name: 'smirking face' }, { emoji: '😒', name: 'unamused face' }, { emoji: '😞', name: 'disappointed face' },
      { emoji: '😔', name: 'pensive face' }, { emoji: '😟', name: 'worried face' }, { emoji: '😕', name: 'confused face' }, { emoji: '🙁', name: 'slightly frowning face' },
      { emoji: '☹️', name: 'frowning face' }, { emoji: '😮', name: 'face with open mouth' }, { emoji: '😯', name: 'hushed face' }, { emoji: '😲', name: 'astonished face' },
      { emoji: '😳', name: 'flushed face' }, { emoji: '🥺', name: 'pleading face' }, { emoji: '😦', name: 'frowning face with open mouth' }, { emoji: '😧', name: 'anguished face' },
      { emoji: '😨', name: 'fearful face' }, { emoji: '😰', name: 'anxious face with sweat' }, { emoji: '😥', name: 'sad but relieved face' }, { emoji: '😢', name: 'crying face' },
      { emoji: '😭', name: 'loudly crying face' }, { emoji: '😱', name: 'face screaming in fear' }, { emoji: '😖', name: 'confounded face' }, { emoji: '😣', name: 'persevering face' },
      { emoji: '😥', name: 'sad but relieved face' }, { emoji: '😮‍💨', name: 'face exhaling' }, { emoji: '😤', name: 'face with steam from nose' },
      { emoji: '😠', name: 'angry face' }, { emoji: '😡', name: 'pouting face' }, { emoji: '🤬', name: 'face with symbols on mouth' }, { emoji: '🤯', name: 'exploding head' },
      { emoji: '🥵', name: 'hot face' }, { emoji: '🥶', name: 'cold face' }, { emoji: '😱', name: 'face screaming in fear' }, { emoji: '🤪', name: 'zany face' },
      { emoji: '🤢', name: 'nauseated face' }, { emoji: '🤮', name: 'face vomiting' }, { emoji: '🤧', name: 'sneezing face' }, { emoji: '😷', name: 'face with medical mask' },
      { emoji: '🤒', name: 'face with thermometer' }, { emoji: '🤕', name: 'face with head-bandage' }, { emoji: '🤑', name: 'money-mouth face' }, { emoji: '🤠', name: 'cowboy hat face' },
      { emoji: '😈', name: 'smiling face with horns' }, { emoji: '👿', name: 'angry face with horns' }, { emoji: '🤡', name: 'clown face' }, { emoji: '💩', name: 'pile of poo' },
      { emoji: '👻', name: 'ghost' }, { emoji: '💀', name: 'skull' }, { emoji: '👽', name: 'alien' }, { emoji: '🤖', name: 'robot' }, { emoji: '🎃', name: 'jack-o-lantern' },
      { emoji: '😺', name: 'grinning cat' }, { emoji: '😹', name: 'cat with tears of joy' }, { emoji: '😻', name: 'smiling cat with heart-eyes' }, { emoji: '😼', name: 'cat with wry smile' },
      { emoji: '😽', name: 'kissing cat' }, { emoji: '🙀', name: 'weary cat' }, { emoji: '😿', name: 'crying cat' }, { emoji: '😾', name: 'pouting cat' },
    ]
  },
  {
    name: 'People & Body',
    emojis: [
      { emoji: '👋', name: 'waving hand' }, { emoji: '🤚', name: 'raised back of hand' }, { emoji: '🖐️', name: 'hand with fingers splayed' },
      { emoji: '✋', name: 'raised hand' }, { emoji: '🖖', name: 'vulcan salute' }, { emoji: '👌', name: 'ok hand' },
      { emoji: '🤌', name: 'pinched fingers' }, { emoji: '🤏', name: 'pinching hand' }, { emoji: '✌️', name: 'victory hand' },
      { emoji: '🤞', name: 'crossed fingers' }, { emoji: '🤟', name: 'love-you gesture' }, { emoji: '🤘', name: 'sign of the horns' },
      { emoji: '🤙', name: 'call me hand' }, { emoji: '👈', name: 'backhand index pointing left' }, { emoji: '👉', name: 'backhand index pointing right' },
      { emoji: '👆', name: 'backhand index pointing up' }, { emoji: '🖕', name: 'middle finger' }, { emoji: '👇', name: 'backhand index pointing down' },
      { emoji: '👍', name: 'thumbs up' }, { emoji: '👎', name: 'thumbs down' }, { emoji: '✊', name: 'raised fist' },
      { emoji: '👊', name: 'oncoming fist' }, { emoji: '🤝', name: 'handshake' }, { emoji: '🙏', name: 'folded hands' },
      { emoji: '✍️', name: 'writing hand' }, { emoji: '💅', name: 'nail polish' }, { emoji: '🤳', name: 'selfie' },
      { emoji: '💪', name: 'flexed biceps' }, { emoji: '🦵', name: 'leg' }, { emoji: '🦶', name: 'foot' },
      { emoji: '👂', name: 'ear' }, { emoji: '👃', name: 'nose' }, { emoji: '🧠', name: 'brain' },
      { emoji: '👀', name: 'eyes' }, { emoji: '👁️', name: 'eye' }, { emoji: '👅', name: 'tongue' },
      { emoji: '👄', name: 'mouth' }, { emoji: '👶', name: 'baby' }, { emoji: '👧', name: 'girl' },
      { emoji: '👦', name: 'boy' }, { emoji: '👩', name: 'woman' }, { emoji: '👨', name: 'man' }, { emoji: '🧑', name: 'person' },
      { emoji: '👱', name: 'person: blond hair' }, { emoji: '🧑‍🦰', name: 'person: red hair' }, { emoji: '🧑‍🦱', name: 'person: curly hair' },
      { emoji: '🧑‍🦳', name: 'person: white hair' }, { emoji: '🧑‍🦲', name: 'person: bald' }, { emoji: '🧔', name: 'person: beard' },
      { emoji: '👵', name: 'old woman' }, { emoji: '👴', name: 'old man' }, { emoji: '🧓', name: 'older person' },
      { emoji: '👲', name: 'person with skullcap' }, { emoji: '👳', name: 'person wearing turban' }, { emoji: '🧕', name: 'woman with headscarf' },
      { emoji: '👮', name: 'police officer' }, { emoji: '👷', name: 'construction worker' }, { emoji: '💂', name: 'guard' },
      { emoji: '🕵️', name: 'detective' }, { emoji: '🧑‍⚕️', name: 'health worker' }, { emoji: '🧑‍🌾', name: 'farmer' },
      { emoji: '🧑‍🍳', name: 'cook' }, { emoji: '🧑‍🎓', name: 'student' }, { emoji: '🧑‍🎤', name: 'singer' },
      { emoji: '🧑‍🏫', name: 'teacher' }, { emoji: '🧑‍🏭', name: 'factory worker' }, { emoji: '🧑‍💻', name: 'technologist' },
      { emoji: '🧑‍💼', name: 'office worker' }, { emoji: '🧑‍🔧', name: 'mechanic' }, { emoji: '🧑‍🔬', name: 'scientist' },
      { emoji: '🧑‍🎨', name: 'artist' }, { emoji: '🧑‍🚒', name: 'firefighter' }, { emoji: '🧑‍✈️', name: 'pilot' },
      { emoji: '🧑‍🚀', name: 'astronaut' }, { emoji: '🧑‍⚖️', name: 'judge' }, { emoji: '🤴', name: 'prince' },
      { emoji: '👸', name: 'princess' }, { emoji: '🦸', name: 'superhero' }, { emoji: '🦹', name: 'supervillain' },
      { emoji: '🧙', name: 'mage' }, { emoji: '🧛', name: 'vampire' }, { emoji: '🧜', name: 'merperson' },
      { emoji: '🧝', name: 'elf' }, { emoji: '🧞', name: 'genie' }, { emoji: '🧟', name: 'zombie' },
    ],
  },
  {
    name: 'Animals & Nature',
    emojis: [
        { emoji: '🐶', name: 'dog face' }, { emoji: '🐱', name: 'cat face' }, { emoji: '🐭', name: 'mouse face' },
        { emoji: '🐹', name: 'hamster face' }, { emoji: '🐰', name: 'rabbit face' }, { emoji: '🦊', name: 'fox face' },
        { emoji: '🐻', name: 'bear face' }, { emoji: '🐼', name: 'panda face' }, { emoji: '🐨', name: 'koala' },
        { emoji: '🐯', name: 'tiger face' }, { emoji: '🦁', name: 'lion face' }, { emoji: '🐮', name: 'cow face' },
        { emoji: '🐷', name: 'pig face' }, { emoji: '🐸', name: 'frog face' }, { emoji: '🐵', name: 'monkey face' },
        { emoji: '🙈', name: 'see-no-evil monkey' }, { emoji: '🙉', name: 'hear-no-evil monkey' }, { emoji: '🙊', name: 'speak-no-evil monkey' },
        { emoji: '🐔', name: 'chicken' }, { emoji: '🐧', name: 'penguin' }, { emoji: '🐦', name: 'bird' }, { emoji: '🐤', name: 'baby chick' },
        { emoji: '🦆', name: 'duck' }, { emoji: '🦅', name: 'eagle' }, { emoji: '🦉', name: 'owl' }, { emoji: '🦇', name: 'bat' },
        { emoji: '🐺', name: 'wolf face' }, { emoji: '🐗', name: 'boar' }, { emoji: '🐴', name: 'horse face' },
        { emoji: '🦄', name: 'unicorn face' }, { emoji: '🐝', name: 'honeybee' }, { emoji: '🐛', name: 'bug' },
        { emoji: '🦋', name: 'butterfly' }, { emoji: '🐌', name: 'snail' }, { emoji: '🐞', name: 'lady beetle' },
        { emoji: '🐜', name: 'ant' }, { emoji: '🦗', name: 'cricket' }, { emoji: '🕷️', name: 'spider' },
        { emoji: '🦂', name: 'scorpion' }, { emoji: '🦟', name: 'mosquito' }, { emoji: '🐢', name: 'turtle' },
        { emoji: '🐍', name: 'snake' }, { emoji: '🦎', name: 'lizard' }, { emoji: '🦖', name: 'T-Rex' },
        { emoji: '🦕', name: 'sauropod' }, { emoji: '🐙', name: 'octopus' }, { emoji: '🦑', name: 'squid' },
        { emoji: '🦐', name: 'shrimp' }, { emoji: '🦞', name: 'lobster' }, { emoji: '🦀', name: 'crab' },
        { emoji: '🐡', name: 'blowfish' }, { emoji: '🐠', name: 'tropical fish' }, { emoji: '🐟', name: 'fish' },
        { emoji: '🐬', name: 'dolphin' }, { emoji: '🐳', name: 'spouting whale' }, { emoji: '🐋', name: 'whale' },
        { emoji: '🦈', name: 'shark' }, { emoji: '🐊', name: 'crocodile' }, { emoji: '🐅', name: 'tiger' },
        { emoji: '🐆', name: 'leopard' }, { emoji: '🦓', name: 'zebra' }, { emoji: '🦍', name: 'gorilla' },
        { emoji: '🦧', name: 'orangutan' }, { emoji: '🐘', name: 'elephant' }, { emoji: '🦛', name: 'hippopotamus' },
        { emoji: '🦏', name: 'rhinoceros' }, { emoji: '🐪', name: 'camel' }, { emoji: '🦒', name: 'giraffe' },
        { emoji: '🦘', name: 'kangaroo' }, { emoji: '🐃', name: 'water buffalo' }, { emoji: '🐂', name: 'ox' },
        { emoji: '🐄', name: 'cow' }, { emoji: '🐎', name: 'horse' }, { emoji: '🐖', name: 'pig' }, { emoji: '🐏', name: 'ram' },
        { emoji: '🐐', name: 'goat' }, { emoji: '🦌', name: 'deer' }, { emoji: '🐕', name: 'dog' }, { emoji: '🐩', name: 'poodle' },
        { emoji: '🐈', name: 'cat' }, { emoji: '🐓', name: 'rooster' }, { emoji: '🦃', name: 'turkey' }, { emoji: '🕊️', name: 'dove' },
        { emoji: '🐇', name: 'rabbit' }, { emoji: '🐁', name: 'mouse' }, { emoji: '🐀', name: 'rat' }, { emoji: '🐿️', name: 'chipmunk' },
        { emoji: '🦔', name: 'hedgehog' }, { emoji: '🐾', name: 'paw prints' }, { emoji: '🐉', name: 'dragon' },
        { emoji: '🐲', name: 'dragon face' }, { emoji: '🌵', name: 'cactus' }, { emoji: '🎄', name: 'Christmas tree' },
        { emoji: '🌲', name: 'evergreen tree' }, { emoji: '🌳', name: 'deciduous tree' }, { emoji: '🌴', name: 'palm tree' },
        { emoji: '🌱', name: 'seedling' }, { emoji: '🌿', name: 'herb' }, { emoji: '☘️', name: 'shamrock' },
        { emoji: '🍀', name: 'four leaf clover' }, { emoji: '🎍', name: 'pine decoration' }, { emoji: '🍂', name: 'fallen leaf' },
        { emoji: '🍃', name: 'leaf fluttering in wind' }, { emoji: '🍄', name: 'mushroom' }, { emoji: '🌾', name: 'sheaf of rice' },
        { emoji: '💐', name: 'bouquet' }, { emoji: '🌷', name: 'tulip' }, { emoji: '🌹', name: 'rose' }, { emoji: '🥀', name: 'wilted flower' },
        { emoji: '🌻', name: 'sunflower' }, { emoji: '🌼', name: 'blossom' }, { emoji: '🌸', name: 'cherry blossom' },
        { emoji: '🌎', name: 'globe showing Americas' }, { emoji: '🌞', name: 'sun with face' }, { emoji: '⭐', name: 'star' },
        { emoji: '🌟', name: 'glowing star' }, { emoji: '🔥', name: 'fire' }, { emoji: '💧', name: 'droplet' }, { emoji: '🌊', name: 'water wave' }
    ]
  },
  {
    name: 'Food & Drink',
    emojis: [
        { emoji: '🍇', name: 'grapes' }, { emoji: '🍈', name: 'melon' }, { emoji: '🍉', name: 'watermelon' },
        { emoji: '🍊', name: 'tangerine' }, { emoji: '🍋', name: 'lemon' }, { emoji: '🍌', name: 'banana' },
        { emoji: '🍍', name: 'pineapple' }, { emoji: '🥭', name: 'mango' }, { emoji: '🍎', name: 'red apple' },
        { emoji: '🍏', name: 'green apple' }, { emoji: '🍐', name: 'pear' }, { emoji: '🍑', name: 'peach' },
        { emoji: '🍒', name: 'cherries' }, { emoji: '🍓', name: 'strawberry' }, { emoji: '🥝', name: 'kiwi fruit' },
        { emoji: '🍅', name: 'tomato' }, { emoji: '🥥', name: 'coconut' }, { emoji: '🥑', name: 'avocado' },
        { emoji: '🍆', name: 'eggplant' }, { emoji: '🥔', name: 'potato' }, { emoji: '🥕', name: 'carrot' },
        { emoji: '🌽', name: 'ear of corn' }, { emoji: '🌶️', name: 'hot pepper' }, { emoji: '🥒', name: 'cucumber' },
        { emoji: '🥬', name: 'leafy green' }, { emoji: '🥦', name: 'broccoli' }, { emoji: '🧄', name: 'garlic' },
        { emoji: '🧅', name: 'onion' }, { emoji: '🥜', name: 'peanuts' }, { emoji: '🌰', name: 'chestnut' },
        { emoji: '🍞', name: 'bread' }, { emoji: '🥐', name: 'croissant' }, { emoji: '🥖', name: 'baguette bread' },
        { emoji: '🥨', name: 'pretzel' }, { emoji: '🥯', name: 'bagel' }, { emoji: '🥞', name: 'pancakes' },
        { emoji: '🧇', name: 'waffle' }, { emoji: '🧀', name: 'cheese wedge' }, { emoji: '🍖', name: 'meat on bone' },
        { emoji: '🍗', name: 'poultry leg' }, { emoji: '🥩', name: 'cut of meat' }, { emoji: '🥓', name: 'bacon' },
        { emoji: '🍔', name: 'hamburger' }, { emoji: '🍟', name: 'french fries' }, { emoji: '🍕', name: 'pizza' },
        { emoji: '🌭', name: 'hot dog' }, { emoji: '🥪', name: 'sandwich' }, { emoji: '🌮', name: 'taco' },
        { emoji: '🌯', name: 'burrito' }, { emoji: '🥙', name: 'stuffed flatbread' }, { emoji: '🧆', name: 'falafel' },
        { emoji: '🥚', name: 'egg' }, { emoji: '🍳', name: 'cooking' }, { emoji: '🥘', name: 'shallow pan of food' },
        { emoji: '🍲', name: 'pot of food' }, { emoji: '🥣', name: 'bowl with spoon' }, { emoji: '🥗', name: 'green salad' },
        { emoji: '🍿', name: 'popcorn' }, { emoji: '🧈', name: 'butter' }, { emoji: '🧂', name: 'salt' },
        { emoji: '🥫', name: 'canned food' }, { emoji: '🍱', name: 'bento box' }, { emoji: '🍘', name: 'rice cracker' },
        { emoji: '🍙', name: 'rice ball' }, { emoji: '🍚', name: 'cooked rice' }, { emoji: '🍛', name: 'curry rice' },
        { emoji: '🍜', name: 'steaming bowl' }, { emoji: '🍝', name: 'spaghetti' }, { emoji: '🍠', name: 'roasted sweet potato' },
        { emoji: '🍣', name: 'sushi' }, { emoji: '🍤', name: 'fried shrimp' }, { emoji: '🍥', name: 'fish cake with swirl' },
        { emoji: '🥮', name: 'moon cake' }, { emoji: '🍡', name: 'dango' }, { emoji: '🥟', name: 'dumpling' },
        { emoji: '🥠', name: 'fortune cookie' }, { emoji: '🥡', name: 'takeout box' }, { emoji: '🦪', name: 'oyster' },
        { emoji: '🍦', name: 'soft ice cream' }, { emoji: '🍧', name: 'shaved ice' }, { emoji: '🍨', name: 'ice cream' },
        { emoji: '🍩', name: 'doughnut' }, { emoji: '🍪', name: 'cookie' }, { emoji: '🎂', name: 'birthday cake' },
        { emoji: '🍰', name: 'shortcake' }, { emoji: '🧁', name: 'cupcake' }, { emoji: '🥧', name: 'pie' },
        { emoji: '🍫', name: 'chocolate bar' }, { emoji: '🍬', name: 'candy' }, { emoji: '🍭', name: 'lollipop' },
        { emoji: '🍮', name: 'custard' }, { emoji: '🍯', name: 'honey pot' }, { emoji: '🍼', name: 'baby bottle' },
        { emoji: '🥛', name: 'glass of milk' }, { emoji: '☕', name: 'hot beverage' }, { emoji: '🍵', name: 'teacup without handle' },
        { emoji: '🥤', name: 'cup with straw' }, { emoji: '🧋', name: 'bubble tea' }, { emoji: '🍶', name: 'sake' },
        { emoji: '🍺', name: 'beer mug' }, { emoji: '🍻', name: 'clinking beer mugs' }, { emoji: '🥂', name: 'clinking glasses' },
        { emoji: '🍷', name: 'wine glass' }, { emoji: '🥃', name: 'tumbler glass' }, { emoji: '🍸', name: 'cocktail glass' },
        { emoji: '🍹', name: 'tropical drink' }, { emoji: '🧉', name: 'mate' }, { emoji: '🧊', name: 'ice' }
    ]
  },
  {
    name: 'Activities',
    emojis: [
        { emoji: '⚽', name: 'soccer ball' }, { emoji: '🏀', name: 'basketball' }, { emoji: '🏈', name: 'american football' },
        { emoji: '⚾', name: 'baseball' }, { emoji: '🥎', name: 'softball' }, { emoji: '🎾', name: 'tennis' },
        { emoji: '🏐', name: 'volleyball' }, { emoji: '🏉', name: 'rugby football' }, { emoji: '🎱', name: 'pool 8 ball' },
        { emoji: '🥏', name: 'flying disc' }, { emoji: '🎳', name: 'bowling' }, { emoji: '🏏', name: 'cricket game' },
        { emoji: '🏑', name: 'field hockey' }, { emoji: '🏒', name: 'ice hockey' }, { emoji: '🥍', name: 'lacrosse' },
        { emoji: '🏓', name: 'ping pong' }, { emoji: '🏸', name: 'badminton' }, { emoji: '🥊', name: 'boxing glove' },
        { emoji: '🥋', name: 'martial arts uniform' }, { emoji: '🥅', name: 'goal net' }, { emoji: '⛳', name: 'flag in hole' },
        { emoji: '⛸️', name: 'ice skate' }, { emoji: '🎣', name: 'fishing pole' }, { emoji: '🤿', name: 'diving mask' },
        { emoji: '🎽', name: 'running shirt' }, { emoji: '🎿', name: 'skis' }, { emoji: '🛷', name: 'sled' },
        { emoji: '🥌', name: 'curling stone' }, { emoji: '🎯', name: 'direct hit' }, { emoji: '🎱', name: 'pool 8 ball' },
        { emoji: '🎮', name: 'video game' }, { emoji: '🕹️', name: 'joystick' }, { emoji: '🎲', name: 'game die' },
        { emoji: '🧩', name: 'puzzle piece' }, { emoji: '♟️', name: 'chess pawn' }, { emoji: '🎨', name: 'artist palette' },
        { emoji: '🎬', name: 'clapper board' }, { emoji: '🎤', name: 'microphone' }, { emoji: '🎧', name: 'headphone' },
        { emoji: '🎼', name: 'musical score' }, { emoji: '🎹', name: 'musical keyboard' }, { emoji: '🥁', name: 'drum' },
        { emoji: '🎷', name: 'saxophone' }, { emoji: '🎺', name: 'trumpet' }, { emoji: '🎸', name: 'guitar' },
        { emoji: '🪕', name: 'banjo' }, { emoji: '🎻', name: 'violin' }, { emoji: '🎬', name: 'clapper board' },
        { emoji: '🎭', name: 'performing arts' }, { emoji: '🎪', name: 'circus tent' }, { emoji: '🎟️', name: 'ticket' },
        { emoji: '🏆', name: 'trophy' }, { emoji: '🥇', name: '1st place medal' }, { emoji: '🥈', name: '2nd place medal' },
        { emoji: '🥉', name: '3rd place medal' }
    ]
  },
  {
    name: 'Travel & Places',
    emojis: [
        { emoji: '🚗', name: 'car' }, { emoji: '🚕', name: 'taxi' }, { emoji: '🚙', name: 'jeep' },
        { emoji: '🚌', name: 'bus' }, { emoji: '🚎', name: 'trolleybus' }, { emoji: '🏎️', name: 'racing car' },
        { emoji: '🚓', name: 'police car' }, { emoji: '🚑', name: 'ambulance' }, { emoji: '🚒', name: 'fire engine' },
        { emoji: '🚐', name: 'minibus' }, { emoji: '🚚', name: 'delivery truck' }, { emoji: '🚛', name: 'articulated lorry' },
        { emoji: '🚜', name: 'tractor' }, { emoji: '🛵', name: 'motor scooter' }, { emoji: '🚲', name: 'bicycle' },
        { emoji: '🛴', name: 'kick scooter' }, { emoji: '🛹', name: 'skateboard' }, { emoji: '✈️', name: 'airplane' },
        { emoji: '🚀', name: 'rocket' }, { emoji: '🛸', name: 'flying saucer' }, { emoji: '🚁', name: 'helicopter' },
        { emoji: '🛶', name: 'canoe' }, { emoji: '⛵', name: 'sailboat' }, { emoji: '🚤', name: 'speedboat' },
        { emoji: '🛳️', name: 'passenger ship' }, { emoji: '⛴️', name: 'ferry' }, { emoji: '🚢', name: 'ship' },
        { emoji: '⚓', name: 'anchor' }, { emoji: '⛽', name: 'fuel pump' }, { emoji: '🚧', name: 'construction' },
        { emoji: '🚦', name: 'vertical traffic light' }, { emoji: '🚥', name: 'horizontal traffic light' }, { emoji: '🗺️', name: 'world map' },
        { emoji: '🧭', name: 'compass' }, { emoji: '⛰️', name: 'mountain' }, { emoji: '🌋', name: 'volcano' },
        { emoji: '🗻', name: 'mount fuji' }, { emoji: '🏕️', name: 'camping' }, { emoji: '🏖️', name: 'beach with umbrella' },
        { emoji: '🏜️', name: 'desert' }, { emoji: '🏝️', name: 'desert island' }, { emoji: '🏞️', name: 'national park' },
        { emoji: '🏟️', name: 'stadium' }, { emoji: '🏛️', name: 'classical building' }, { emoji: '🏗️', name: 'building construction' },
        { emoji: '🏘️', name: 'houses' }, { emoji: '🏚️', name: 'derelict house' }, { emoji: '🏠', name: 'house' },
        { emoji: '🏡', name: 'house with garden' }, { emoji: '🏢', name: 'office building' }, { emoji: '🏣', name: 'Japanese post office' },
        { emoji: '🏤', name: 'post office' }, { emoji: '🏥', name: 'hospital' }, { emoji: '🏦', name: 'bank' },
        { emoji: '🏨', name: 'hotel' }, { emoji: '🏪', name: 'convenience store' }, { emoji: '🏫', name: 'school' },
        { emoji: '🏬', name: 'department store' }, { emoji: '🏭', name: 'factory' }, { emoji: '🏯', name: 'Japanese castle' },
        { emoji: '🏰', name: 'castle' }, { emoji: '💒', name: 'wedding' }, { emoji: '🗼', name: 'Tokyo tower' },
        { emoji: '🗽', name: 'Statue of Liberty' }, { emoji: '⛪', name: 'church' }, { emoji: '🕌', name: 'mosque' },
        { emoji: '⛩️', name: 'shinto shrine' }, { emoji: '🕍', name: 'synagogue' }, { emoji: '🕋', name: 'kaaba' },
        { emoji: '⛲', name: 'fountain' }, { emoji: '⛺', name: 'tent' }, { emoji: '🌃', name: 'night with stars' },
        { emoji: '🏙️', name: 'cityscape' }, { emoji: '🌉', name: 'bridge at night' }, { emoji: '🎠', name: 'carousel horse' },
        { emoji: '🎡', name: 'ferris wheel' }, { emoji: '🎢', name: 'roller coaster' }, { emoji: '🚂', name: 'locomotive' },
        { emoji: '🚃', name: 'railway car' }, { emoji: '🚄', name: 'high-speed train' }, { emoji: '🚅', name: 'bullet train' },
        { emoji: '🚆', name: 'train' }, { emoji: '🚇', name: 'metro' }, { emoji: '🚈', name: 'light rail' },
        { emoji: '🚉', name: 'station' }, { emoji: '🚊', name: 'tram' }, { emoji: '🚝', name: 'monorail' }
    ]
  },
  {
    name: 'Objects',
    emojis: [
      { emoji: '⌚', name: 'watch' }, { emoji: '📱', name: 'mobile phone' }, { emoji: '📲', name: 'mobile phone with arrow' },
      { emoji: '💻', name: 'laptop' }, { emoji: '⌨️', name: 'keyboard' }, { emoji: '🖥️', name: 'desktop computer' },
      { emoji: '🖨️', name: 'printer' }, { emoji: '🖱️', name: 'computer mouse' }, { emoji: '🖲️', name: 'trackball' },
      { emoji: '💽', name: 'computer disk' }, { emoji: '💾', name: 'floppy disk' }, { emoji: '💿', name: 'optical disk' },
      { emoji: '📀', name: 'dvd' }, { emoji: '🎥', name: 'movie camera' }, { emoji: '🎞️', name: 'film frames' },
      { emoji: '📽️', name: 'film projector' }, { emoji: '📺', name: 'television' }, { emoji: '📷', name: 'camera' },
      { emoji: '📸', name: 'camera with flash' }, { emoji: '📹', name: 'video camera' }, { emoji: '📼', name: 'videocassette' },
      { emoji: '🔍', name: 'magnifying glass tilted left' }, { emoji: '🔎', name: 'magnifying glass tilted right' },
      { emoji: '🕯️', name: 'candle' }, { emoji: '💡', name: 'light bulb' }, { emoji: '🔦', name: 'flashlight' },
      { emoji: '🏮', name: 'red paper lantern' }, { emoji: '📔', name: 'notebook with decorative cover' }, { emoji: '📕', name: 'closed book' },
      { emoji: '📖', name: 'open book' }, { emoji: '📗', name: 'green book' }, { emoji: '📘', name: 'blue book' },
      { emoji: '📙', name: 'orange book' }, { emoji: '📚', name: 'books' }, { emoji: '📓', name: 'notebook' },
      { emoji: '📃', name: 'page with curl' }, { emoji: '📜', name: 'scroll' }, { emoji: '📄', name: 'page facing up' },
      { emoji: '📰', name: 'newspaper' }, { emoji: '🗞️', name: 'rolled-up newspaper' }, { emoji: '📑', name: 'bookmark tabs' },
      { emoji: '🔖', name: 'bookmark' }, { emoji: '🏷️', name: 'label' }, { emoji: '💰', name: 'money bag' },
      { emoji: '💴', name: 'yen banknote' }, { emoji: '💵', name: 'dollar banknote' }, { emoji: '💶', name: 'euro banknote' },
      { emoji: '💷', name: 'pound banknote' }, { emoji: '💸', name: 'money with wings' }, { emoji: '💳', name: 'credit card' },
      { emoji: '🧾', name: 'receipt' }, { emoji: '✉️', name: 'envelope' }, { emoji: '📧', name: 'e-mail' },
      { emoji: '📨', name: 'incoming envelope' }, { emoji: '📩', name: 'envelope with arrow' }, { emoji: '📤', name: 'outbox tray' },
      { emoji: '📥', name: 'inbox tray' }, { emoji: '📦', name: 'package' }, { emoji: '📫', name: 'closed mailbox with raised flag' },
      { emoji: '📪', name: 'closed mailbox with lowered flag' }, { emoji: '📬', name: 'open mailbox with raised flag' },
      { emoji: '📭', name: 'open mailbox with lowered flag' }, { emoji: '📮', name: 'postbox' }, { emoji: '🗳️', name: 'ballot box with ballot' },
      { emoji: '✏️', name: 'pencil' }, { emoji: '✒️', name: 'black nib' }, { emoji: '🖋️', name: 'fountain pen' },
      { emoji: '🖊️', name: 'pen' }, { emoji: '🖌️', name: 'paintbrush' }, { emoji: '🖍️', name: 'crayon' },
      { emoji: '📁', name: 'file folder' }, { emoji: '📂', name: 'open file folder' }, { emoji: '🗂️', name: 'card index dividers' },
      { emoji: '📅', name: 'calendar' }, { emoji: '📆', name: 'tear-off calendar' }, { emoji: '🗒️', name: 'spiral notepad' },
      { emoji: '🗓️', name: 'spiral calendar' }, { emoji: '📇', name: 'card index' }, { emoji: '📈', name: 'chart increasing' },
      { emoji: '📉', name: 'chart decreasing' }, { emoji: '📊', name: 'bar chart' }, { emoji: '📋', name: 'clipboard' },
      { emoji: '📌', name: 'pushpin' }, { emoji: '📍', name: 'round pushpin' }, { emoji: '📎', name: 'paperclip' },
      { emoji: '🖇️', name: 'linked paperclips' }, { emoji: '📏', name: 'straight ruler' }, { emoji: '📐', name: 'triangular ruler' },
      { emoji: '✂️', name: 'scissors' }, { emoji: '🗃️', name: 'card file box' }, { emoji: '🗄️', name: 'file cabinet' },
      { emoji: '🗑️', name: 'wastebasket' }, { emoji: '🔒', name: 'locked' }, { emoji: '🔓', name: 'unlocked' },
      { emoji: '🔏', name: 'locked with pen' }, { emoji: '🔐', name: 'locked with key' }, { emoji: '🔑', name: 'key' },
      { emoji: '🗝️', name: 'old key' }, { emoji: '🔨', name: 'hammer' }, { emoji: '🪓', name: 'axe' },
      { emoji: '⛏️', name: 'pick' }, { emoji: '⚒️', name: 'hammer and pick' }, { emoji: '🛠️', name: 'hammer and wrench' },
      { emoji: '🗡️', name: 'dagger' }, { emoji: '⚔️', name: 'crossed swords' }, { emoji: '🔫', name: 'pistol' },
      { emoji: '🛡️', name: 'shield' }, { emoji: '🔧', name: 'wrench' }, { emoji: '🔩', name: 'nut and bolt' },
      { emoji: '⚙️', name: 'gear' }, { emoji: '🗜️', name: 'clamp' }, { emoji: '⚖️', name: 'balance scale' },
      { emoji: '🔗', name: 'link' }, { emoji: '⛓️', name: 'chains' }, { emoji: '🧰', name: 'toolbox' },
      { emoji: '🧲', name: 'magnet' }, { emoji: '⚗️', name: 'alembic' }, { emoji: '🧪', name: 'test tube' },
      { emoji: '🧫', name: 'petri dish' }, { emoji: '🧬', name: 'dna' }, { emoji: '🔬', name: 'microscope' },
      { emoji: '🔭', name: 'telescope' }, { emoji: '📡', name: 'satellite antenna' }, { emoji: '💉', name: 'syringe' },
      { emoji: '🩸', name: 'drop of blood' }, { emoji: '💊', name: 'pill' }, { emoji: '🩹', name: 'adhesive bandage' },
      { emoji: '🩺', name: 'stethoscope' }, { emoji: '🚪', name: 'door' }, { emoji: '🛏️', name: 'bed' },
      { emoji: '🛋️', name: 'couch and lamp' }, { emoji: '🪑', name: 'chair' }, { emoji: '🚽', name: 'toilet' },
      { emoji: '🚿', name: 'shower' }, { emoji: '🛁', name: 'bathtub' }, { emoji: '🚬', name: 'cigarette' },
      { emoji: '⚰️', name: 'coffin' }, { emoji: '⚱️', name: 'funeral urn' }, { emoji: '🗿', name: 'moai' },
    ]
  },
  {
    name: 'Symbols',
    emojis: [
      { emoji: '❤️', name: 'red heart' }, { emoji: '🧡', name: 'orange heart' }, { emoji: '💛', name: 'yellow heart' },
      { emoji: '💚', name: 'green heart' }, { emoji: '💙', name: 'blue heart' }, { emoji: '💜', name: 'purple heart' },
      { emoji: '🖤', name: 'black heart' }, { emoji: '🤍', name: 'white heart' }, { emoji: '🤎', name: 'brown heart' },
      { emoji: '💔', name: 'broken heart' }, { emoji: '❣️', name: 'heart exclamation' }, { emoji: '💕', name: 'two hearts' },
      { emoji: '💞', name: 'revolving hearts' }, { emoji: '💓', name: 'beating heart' }, { emoji: '💗', name: 'growing heart' },
      { emoji: '💖', name: 'sparkling heart' }, { emoji: '💘', name: 'heart with arrow' }, { emoji: '💝', name: 'heart with ribbon' },
      { emoji: '💟', name: 'heart decoration' }, { emoji: '☮️', name: 'peace symbol' }, { emoji: '✝️', name: 'latin cross' },
      { emoji: '☪️', name: 'star and crescent' }, { emoji: '🕉️', name: 'om' }, { emoji: '☸️', name: 'wheel of dharma' },
      { emoji: '✡️', name: 'star of David' }, { emoji: '🔯', name: 'dotted six-pointed star' }, { emoji: '🕎', name: 'menorah' },
      { emoji: '☯️', name: 'yin yang' }, { emoji: '☦️', name: 'orthodox cross' }, { emoji: '🛐', name: 'place of worship' },
      { emoji: '⛎', name: 'Ophiuchus' }, { emoji: '♈', name: 'Aries' }, { emoji: '♉', name: 'Taurus' },
      { emoji: '♊', name: 'Gemini' }, { emoji: '♋', name: 'Cancer' }, { emoji: '♌', name: 'Leo' },
      { emoji: '♍', name: 'Virgo' }, { emoji: '♎', name: 'Libra' }, { emoji: '♏', name: 'Scorpio' },
      { emoji: '♐', name: 'Sagittarius' }, { emoji: '♑', name: 'Capricorn' }, { emoji: '♒', name: 'Aquarius' },
      { emoji: '♓', name: 'Pisces' }, { emoji: '🆔', name: 'ID button' }, { emoji: '⚛️', name: 'atom symbol' },
      { emoji: '🈳', name: 'Japanese “vacancy” button' }, { emoji: '☢️', name: 'radioactive' }, { emoji: '☣️', name: 'biohazard' },
      { emoji: '📳', name: 'vibration mode' }, { emoji: '📴', name: 'mobile phone off' }, { emoji: '🈶', name: 'Japanese “not free of charge” button' },
      { emoji: '🈚', name: 'Japanese “free of charge” button' }, { emoji: '🈺', name: 'Japanese “open for business” button' },
      { emoji: '🈷️', name: 'Japanese “monthly amount” button' }, { emoji: '✴️', name: 'eight-pointed star' }, { emoji: '🆚', name: 'vs button' },
      { emoji: '🉑', name: 'Japanese “acceptable” button' }, { emoji: '💮', name: 'white flower' }, { emoji: '🉐', name: 'Japanese “bargain” button' },
      { emoji: '㊙️', name: 'Japanese “secret” button' }, { emoji: '㊗️', name: 'Japanese “congratulations” button' }, { emoji: '🆎', name: 'ab button blood type' },
      { emoji: '🅱️', name: 'b button blood type' }, { emoji: '🅾️', name: 'o button blood type' }, { emoji: '🆘', name: 'sos button' },
      { emoji: '❌', name: 'cross mark' }, { emoji: '⭕', name: 'hollow red circle' }, { emoji: '🛑', name: 'stop sign' },
      { emoji: '⛔', name: 'no entry' }, { emoji: '📛', name: 'name badge' }, { emoji: '🚫', name: 'prohibited' },
      { emoji: '💯', name: 'hundred points' }, { emoji: '💢', name: 'anger symbol' }, { emoji: '❓', name: 'red question mark' },
      { emoji: '❔', name: 'white question mark' }, { emoji: '❕', name: 'white exclamation mark' }, { emoji: '❗', name: 'red exclamation mark' },
      { emoji: '〰️', name: 'wavy dash' }, { emoji: '♾️', name: 'infinity' }, { emoji: '✅', name: 'check mark button' },
      { emoji: '✔️', name: 'check mark' }, { emoji: '➕', name: 'plus' }, { emoji: '➖', name: 'minus' },
      { emoji: '➗', name: 'divide' }, { emoji: '✖️', name: 'multiply' }, { emoji: '💲', name: 'heavy dollar sign' },
      { emoji: '©️', name: 'copyright' }, { emoji: '®️', name: 'registered' }, { emoji: '™️', name: 'trade mark' },
      { emoji: '#️⃣', name: 'hash key' }, { emoji: '*️⃣', name: 'keycap asterisk' }, { emoji: '0️⃣', name: 'keycap 0' },
      { emoji: '1️⃣', name: 'keycap 1' }, { emoji: '2️⃣', name: 'keycap 2' }, { emoji: '3️⃣', name: 'keycap 3' },
      { emoji: '4️⃣', name: 'keycap 4' }, { emoji: '5️⃣', name: 'keycap 5' }, { emoji: '6️⃣', name: 'keycap 6' },
      { emoji: '7️⃣', name: 'keycap 7' }, { emoji: '8️⃣', name: 'keycap 8' }, { emoji: '9️⃣', name: 'keycap 9' },
      { emoji: '🔟', name: 'keycap 10' }, { emoji: '▶️', name: 'play button' }, { emoji: '⏸️', name: 'pause button' },
      { emoji: '⏹️', name: 'stop button' }, { emoji: '⏺️', name: 'record button' }, { emoji: '🔼', name: 'upwards button' },
      { emoji: '🔽', name: 'downwards button' }, { emoji: '⏫', name: 'fast up button' }, { emoji: '⏬', name: 'fast down button' },
      { emoji: '➡️', name: 'right arrow' }, { emoji: '⬅️', name: 'left arrow' }, { emoji: '⬆️', name: 'up arrow' },
      { emoji: '⬇️', name: 'down arrow' }, { emoji: '↗️', name: 'up-right arrow' }, { emoji: '↘️', name: 'down-right arrow' },
      { emoji: '↙️', name: 'down-left arrow' }, { emoji: '↖️', name: 'up-left arrow' }, { emoji: '↕️', name: 'up-down arrow' },
      { emoji: '↔️', name: 'left-right arrow' }, { emoji: '↩️', name: 'right arrow curving left' }, { emoji: '↪️', name: 'left arrow curving right' },
      { emoji: '⤴️', name: 'right arrow curving up' }, { emoji: '⤵️', name: 'right arrow curving down' }, { emoji: '🔄', name: 'counterclockwise arrows button' }
    ]
  },
  {
    name: 'Flags',
    emojis: [
      { emoji: '🏁', name: 'chequered flag' }, { emoji: '🚩', name: 'triangular flag' }, { emoji: '🎌', name: 'crossed flags' },
      { emoji: '🏴', name: 'black flag' }, { emoji: '🏳️', name: 'white flag' }, { emoji: '🏳️‍🌈', name: 'rainbow flag' },
      { emoji: '🏳️‍⚧️', name: 'transgender flag' }, { emoji: '🏴‍☠️', name: 'pirate flag' },
      { emoji: '🇺🇸', name: 'flag: United States' }, { emoji: '🇬🇧', name: 'flag: United Kingdom' }, { emoji: '🇨🇦', name: 'flag: Canada' },
      { emoji: '🇫🇷', name: 'flag: France' }, { emoji: '🇩🇪', name: 'flag: Germany' }, { emoji: '🇮🇹', name: 'flag: Italy' },
      { emoji: '🇪🇸', name: 'flag: Spain' }, { emoji: '🇯🇵', name: 'flag: Japan' }, { emoji: '🇨🇳', name: 'flag: China' },
      { emoji: '🇰🇷', name: 'flag: South Korea' }, { emoji: '🇮🇳', name: 'flag: India' }, { emoji: '🇧🇷', name: 'flag: Brazil' },
      { emoji: '🇦🇺', name: 'flag: Australia' }, { emoji: '🇷🇺', name: 'flag: Russia' }, { emoji: '🇲🇽', name: 'flag: Mexico' },
      { emoji: '🇿🇦', name: 'flag: South Africa' }, { emoji: '🇳🇱', name: 'flag: Netherlands' }, { emoji: '🇸🇪', name: 'flag: Sweden' },
      { emoji: '🇳🇴', name: 'flag: Norway' }, { emoji: '🇩🇰', name: 'flag: Denmark' }, { emoji: '🇫🇮', name: 'flag: Finland' },
      { emoji: '🇨🇭', name: 'flag: Switzerland' }, { emoji: '🇦🇹', name: 'flag: Austria' }, { emoji: '🇧🇪', name: 'flag: Belgium' },
      { emoji: '🇵🇹', name: 'flag: Portugal' }, { emoji: '🇬🇷', name: 'flag: Greece' }, { emoji: '🇹🇷', name: 'flag: Turkey' },
      { emoji: '🇪🇬', name: 'flag: Egypt' }, { emoji: '🇸🇦', name: 'flag: Saudi Arabia' }, { emoji: '🇦🇪', name: 'flag: UAE' },
      { emoji: '🇮🇱', name: 'flag: Israel' }, { emoji: '🇮🇷', name: 'flag: Iran' }, { emoji: '🇮🇶', name: 'flag: Iraq' },
      { emoji: '🇵🇰', name: 'flag: Pakistan' }, { emoji: '🇧🇩', name: 'flag: Bangladesh' }, { emoji: '🇱🇰', name: 'flag: Sri Lanka' },
      { emoji: '🇹🇭', name: 'flag: Thailand' }, { emoji: '🇻🇳', name: 'flag: Vietnam' }, { emoji: '🇵🇭', name: 'flag: Philippines' },
      { emoji: '🇮🇩', name: 'flag: Indonesia' }, { emoji: '🇲🇾', name: 'flag: Malaysia' }, { emoji: '🇸🇬', name: 'flag: Singapore' },
      { emoji: '🇳🇿', name: 'flag: New Zealand' }, { emoji: '🇫🇯', name: 'flag: Fiji' }, { emoji: '🇵🇬', name: 'flag: Papua New Guinea' },
      { emoji: '🇳🇬', name: 'flag: Nigeria' }, { emoji: '🇰🇪', name: 'flag: Kenya' }, { emoji: '🇪🇹', name: 'flag: Ethiopia' },
      { emoji: '🇬🇭', name: 'flag: Ghana' }, { emoji: '🇲🇦', name: 'flag: Morocco' }, { emoji: '🇩🇿', name: 'flag: Algeria' },
      { emoji: '🇹🇳', name: 'flag: Tunisia' }, { emoji: '🇱🇾', name: 'flag: Libya' }, { emoji: '🇸🇩', name: 'flag: Sudan' },
      { emoji: '🇦🇷', name: 'flag: Argentina' }, { emoji: '🇨🇱', name: 'flag: Chile' }, { emoji: '🇵🇪', name: 'flag: Peru' },
      { emoji: '🇨🇴', name: 'flag: Colombia' }, { emoji: '🇻🇪', name: 'flag: Venezuela' }, { emoji: '🇪🇨', name: 'flag: Ecuador' },
      { emoji: '🇺🇾', name: 'flag: Uruguay' }, { emoji: '🇵🇾', name: 'flag: Paraguay' }, { emoji: '🇧🇴', name: 'flag: Bolivia' },
    ]
  },
  {
    name: 'Recent',
    emojis: [
      { emoji: '😀', name: 'grinning face' }, { emoji: '❤️', name: 'red heart' }, { emoji: '👍', name: 'thumbs up' },
      { emoji: '🔥', name: 'fire' }, { emoji: '✨', name: 'sparkles' }, { emoji: '🎉', name: 'party popper' },
      { emoji: '💯', name: 'hundred points' }, { emoji: '🚀', name: 'rocket' }, { emoji: '⭐', name: 'star' },
      { emoji: '💡', name: 'light bulb' }, { emoji: '📝', name: 'memo' }, { emoji: '💻', name: 'laptop' },
    ]
  }
];
